name: CI

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          - macos-11
    name: "Tests [${{ matrix.os }}]"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install shunit2
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Install for integration tests
        run: PREFIX="${RUNNER_TEMP}/chjava" make install
      - name: Setup shells
        run: PREFIX="${RUNNER_TEMP}/chjava" make ci_shell_conf
      - name: Run all tests
        run: PREFIX="${RUNNER_TEMP}/chjava" make ci
